# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null                 # Utilise le gestionnaire de session par défaut (fichiers PHP)
        cookie_lifetime: 0              # Le cookie expire à la fermeture du navigateur
        gc_maxlifetime: 1440            # 24 minutes d’inactivité (en secondes)
        cookie_secure: auto             # sécurise le cookie selon le contexte HTTPS
        cookie_httponly: true           # protège contre l'accès JavaScript
        cookie_samesite: lax            # limite les envois inter-domaines

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file